name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        run: go build
      - name: Format
        run: test -z $(gofmt -l .) || (gofmt -d . && exit 1)
      - uses: actions/upload-artifact@v4
        with:
          path: mdns2mqtt
          if-no-files-found: error
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and load
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: invlid/mdns2mqtt:latest
